### ISSUE TITLE
Issue with neighbors with non-resolving domain names

### ISSUE THREAD

**Issue by bilde2910** [trifel/Report.ixi#11]
There is an issue at iotaledger/ict#18 related to neighbors with domain names that don't resolve that you may want to check if also applies to Report.ixi. You seem to be using the same logic to check for neighbors of incoming packets as ICT. A stack trace from Report.ixi was also generated and posted in the linked ICT issue; the stack trace and more details can be found there. I realized that I never reported the issue here as well when I initially reported it to ICT.

**Comment by ixuz** [comment]
No problem (tested using Ict 0.5 and Report.ixi 0.5.1)
- Tested FQDN resolving ip dynamic change.
- Tested FQDN stops resolving to ip, and then resumes resolving to a completely different ip.

In both cases, both Ict and Report.ixi adapted well to the changes and Report.ixi neighbor configuration was retained all throughout the test.
