### ISSUE TITLE
[feature request] automatic neighbor finder

### ISSUE THREAD

**Issue by a223y** [trifel/Report.ixi#12]
Can't it just try 1338 on node's neighbors?

If not possible, there can be different than JSON format for it's input, because I really have no idea from the web-gui how to format object to be compliant, array of strings doesn't work.

**Comment by trifel** [comment]
hi a223y,

if you save the Report.ixi configuration with the correct `ICT REST API PORT` (= GUI PORT) and the correct `ICT REST API PASSWORD` (= GUI Password), the neighbors will be imported automatically with the default `reportPort` 1338. If you want to change it, you need to configure it in the prefilled JSON-Array for Neighbors (Screenshot). 

As soon we have the chance to optimize the configuration in a better and more easy way, we will do. 

![bildschirmfoto 2019-02-28 um 17 10 28](https://user-images.githubusercontent.com/7024733/53580440-ef1a3880-3b7b-11e9-96fc-c0f5a15ec780.png)

**Comment by ixuz** [comment]
Assuming this issue is resolved.
