### ISSUE TITLE
[feature request] allow cors to fetch json data

### ISSUE THREAD

**Issue by olazpreton** [trifel/Report.ixi#5]
i'm working on an visual representation of the data that is avaiable here: http://api.ictreport.com/nodes.json. it would be fantastic if you can enable cross-origin resource sharing (Access-Control-Allow-Origin: * - https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS ) so that the data can be further processed on client-side e.g. for visual representation of the ict network and oc for other devs with different ideas.

thanks!

**Comment by trifel** [comment]
I added the header for cross-origin resource sharing.
