### ISSUE TITLE
[feature request] add total ping flow from direct neighbors

### ISSUE THREAD

**Issue by olazpreton** [trifel/Report.ixi#6]
for a further evaluation of direct edges to neighbors it would be very helpful if you can add details of the ping flow in a round which are atm aggregatet in this line:

Jan 15 16:16:14 iota java[566]: | 0        | 300   | 0        | Other/Non-neighbor...

example (300 pings total received in a round from 3 direct neighbors):

    "neighbors": [
      {
        "uuid": "c5f919e8-57ca-4a0f-9ffb-cbe8fd3411f1",
        "connectionStatus": "ACTIVE",
        "receivingPings": true,
        "pingFlow":120
      },
      {
        "uuid": "86780448-07ab-441b-ae34-501519389347",
        "connectionStatus": "ACTIVE",
        "receivingPings": true,
        "pingFlow":70
      },
      {
        "uuid": "674bbdce-c2ae-4f32-a6a7-1108b01af2c8",
        "connectionStatus": "ACTIVE",
        "receivingPings": true,
        "pingFlow":110
      }

the data could than merged per edge with the other side and recalculated for visual weight to see the "main roads" of the ping (transaction) flow in an network visualisation.

thanks!

**Comment by trifel** [comment]
Since version 0.5 it is possible to use the metrics for further weight calculations. Currently the test pings are only used to measure the reach.
