### ISSUE TITLE
[feature request] rethink uuid sheme on provided json files

### ISSUE THREAD

**Issue by olazpreton** [trifel/Report.ixi#9]
as the network will grow it could maybe a good idea to map the uuid's to consecutive numbering (only in the json files oc)

example:
all uuid's in the file that match d885fbf8-08a6-4e14-b29c-57abcbcbd5ac = 1, 
all uuid's in the file that match 018f137b-ed5e-4d5d-bd76-28d21f5e801c = 2,
etc

this will keep the json files small (if the real id is not needed ... there is also the name to identify)

if there will be json files by request one could choose between real uuid and other shemes

**Comment by trifel** [comment]
The uuids were replaced by ids:
https://api.ictreport.com/nodes.json
https://api.ictreport.com/transactions.json
